apiVersion: v1
kind: Service
metadata:
  name: examples-node-app
  namespace: example-node-app
  labels:
    name: example-node-app
spec:
  selector:             # selects pods with these labels
    app_name: example-node-app
    app_version: 1.1.1
  type: NodePort
  ports:
    - name: http
      port: 80          # service port
      protocol: TCP
      targetPort: 3000  # pod port
